export enum ObjectType {
  Mat = 'mat',
  MatVector = 'mat_vector',
  Point = 'point',
  Point2f = 'point2f',
  PointVector = 'point_vector',
  PointVectorOfVectors = 'point_vector_vector',
  Point2fVector = 'point2f_vector',
  Rect = 'rect',
  RectVector = 'rect_vector',
  Size = 'size',
  Vec3b = 'vec3b',
  Scalar = 'scalar',
  RotatedRect = 'rotated_rect',
  TermCriteria = 'term_criteria',
}
